export const TYPES = {
	JwtAuth: Symbol.for("JwtAuth"),
	AuthService: Symbol.for("AuthService"),
	AuthController: Symbol.for("AuthController"),
	AuthRoutes: Symbol.for("AuthRoutes"),
	UserRepository: Symbol.for("UserRepository"),
	UserService: Symbol.for("UserService"),
	UserController: Symbol.for("UserController"),
	UserRoutes: Symbol.for("UserRoutes"),
	ImageRepository: Symbol.for("ImageRepository"),
	ImageService: Symbol.for("ImageService"),
	ImageController: Symbol.for("ImageController"),
	ImageRoutes: Symbol.for("ImageRoutes"),
	NotFoundController: Symbol.for("NotFoundController"),
	NotFoundRoutes: Symbol.for("NotFoundRoutes"),
	Routes: Symbol.for("Routes"),
	Middlewares: Symbol.for("Middlewares"),
	App: Symbol.for("App"),
};
